# Generated by Django 3.1.4 on 2021-03-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='MyImage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
